### ISSUE TITLE
No Pagination

### ISSUE THREAD

**Issue by alondahari** [nnarhinen/react-pdf#47]
Hi again,
What do you think would be the best way to use your package if I don't want pagination with my PDF, e.g. be able to simply scroll down through the whole document?

Thanks!

**Comment by wojtekmaj** [comment]
Hi!
For that, I would:

1. Create a wrapper that loads the PDF into its state.
1. This wrapper will also have the number of pages in its state. However, we don't know how many will be there yet, so by default, let's put one.
1. Since we know that PDF file has at least one page, we can render the first page using `react-pdf`.
1. From onDocumentLoad callback you will get `total` parameter which will tell you how many pages are there in loaded PDF. Using `setState`, update the number of pages in your wrapper.
1. We can use this number to render as many pages as we would like to.

Sample code (untested, just to illustrate my thought):

```
class Wrapper extends Component {
  state = {
    file: null,
    total: 1,
  }

  componentDidMount() {
    this.loadPdf();
  }

  loadPdf() {
    loadPdfSomehow.then(file =>
      this.setState({ file })
    );
  }

  updateDocumentData({ total }) {
    this.setState({ total });
  }

  render() {
    const { file, total } = this.state;

    return (
      <div>
        {
          Array(total).fill(true).map((el, index) => (
            index === 1 ?
              <ReactPDF file={file} pageIndex={index} onDocumentLoad={this.updateDocumentData} /> :
              <ReactPDF file={file} pageIndex={index} />
          ))
        }
      </div>
    );
  }
}
```

**Comment by ramusus** [comment]
@wojtekmaj your example worth to be in README

**Comment by wojtekmaj** [comment]
@ramusus Just so you know, newest [React-PDF v2.0.0-alpha](https://github.com/wojtekmaj/react-pdf/releases/) supports multiple pages within one `<Document />` component - you may be interested as the efficiency of my workaround above is super poor compared to what the future holds :)

**Comment by ramusus** [comment]
@wojtekmaj Thanks for the improved interface, waiting for the upcoming release!
