### ISSUE TITLE
pdfjs-dist dependency issue

### ISSUE THREAD

**Issue by rob2d** [nnarhinen/react-pdf#54]
Just installed latest version (@1.8.1), and am having an issue with the pdfjs-dist dependency when I try to build using gulp/babel/browserify:
```
Cannot find module 'worker-loader!./build/pdf.worker.js' from 'projectdir\node_modules\pdfjs-dist'
```

Edit: nevermind! Hadn't noticed the new section on webworkers:
https://github.com/wojtekmaj/react-pdf#usage-without-worker

Thanks.

**Comment by wojtekmaj** [comment]
Hey @rob2d, sorry for the inconvenience! Please try the latest (1.8.2). By default it should not load the worker, so just like it was in version 1.6.1 and older. I've also updated instructions on how to opt-in to use workers on Webpack. Browserify support coming later :) Hope this helps, let me know if everything works like a charm out of the box!

**Comment by rob2d** [comment]
Awesome, thanks for that! Unfortunately, it's still a no-go as I use a custom gulp build system :/
(/plug: it's on npm @ `generator-react-redux-gulp` 😄 )

It seems that `builder.worker` which seem related to not supporting Browserify. Right now, I am getting the following error in my console:
![image](https://user-images.githubusercontent.com/1799905/28228127-206e1b68-68ab-11e7-8ba7-4a4eeb4fbfa9.png)

But you seem aware. For now, I am using the fork @ `react-pdf-js`, but not sure if the author is active and the `pdfjs-dist` has some issues on iOS that are probably fixed by now. And npm build scripts don't work for that for some reason 😢 

But in any case thanks for the support and nice work on it in any case! I am looking forward to using it and am glad there's at least a non iOS version that I can use for now.

**Comment by rob2d** [comment]
looks like I'll have to fix this babel config on windows issue after all -- the build created using webpack depends on web workers inherently 😞 

In any case, really appreciate the help!

**Comment by wojtekmaj** [comment]
Hey @rob2d, I'm actually fully commited to supporting browserify. I believe that importing simply 'react-pdf' should work just fine, and in the worst scenario you would just get an attempt to load a non-existing worker.
To fix this, since on browserify I have no control over bundles, you'll have to copy 'pdfjs-dist/build/pdf.worker.js' to build directory on your own. I don't know what the name should be, but pdf.js will request for that file, so when you get 404, you know where you should put it.
